<?xml version="1.0"?>
<package format="2">
  <name>camp</name>
  <version>1.0.0</version>
  <description>The CCOM Autonomous Mission Planner package</description>

  <maintainer email="roland@ccom.unh.edu">Roland Arsenault</maintainer>

  <license>BSD</license>
  
  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>qtpositioning5-dev</build_depend>
  <build_depend>libqt5-svg-dev</build_depend>
  <build_depend>libgdal-dev</build_depend>
  <depend>geometry_msgs</depend>
  <depend>grid_map_ros</depend>
  <depend>marine_ais_msgs</depend>
  <depend>marine_sensor_msgs</depend>

  <depend>message_filters</depend>
  <depend>nav_msgs</depend>
  <depend>nav2_msgs</depend>
  <depend>pluginlib</depend>
  <depend>marine_autonomy</depend>
  <depend>marine_colormap</depend>
  <depend>marine_colormap_widgets</depend>
  <depend>marine_interfaces</depend>
  <depend>marine_tiled_raster_store</depend>
  <depend>marine_nav_interfaces</depend>
  <depend>marine_nav_tasks</depend>

  <!-- <depend>sound_play</depend> -->
  <depend>tf2</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>rqt_gui_cpp</depend>
  <depend>rqt_gui</depend>
  <depend>yaml-cpp</depend>
  
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>

